package com.example.android.arimdb;

/**
 * Created by ASUS GL553VD on 8/17/2017.
 */

public final class MovieBox {
    /**
     * This method returns a list of popular movie names from the 20th and early 21st centuries.
     *
     * @return A list of popular movies
     */

    public static String[] getMovieNames() {
        return new String[] {
            "Star Wars: Episode VII - The Force Awakens (2015)",
            "Avatar (2009)",
            "Titanic (1997)",
            "Jurassic World (2015)",
            "Marvel's The Avengers (2012)",
            "The Dark Knight (2008)",
            "Rogue One: A Star Wars Story (2016)",
            "Beauty and the Beast (2017)",
            "Finding Dory (2016)",
            "Star Wars: Episode I - The Phantom Menace (1999)",
            "Star Wars: Episode IV - A New Hope (1977)",
            "Avengers: Age of Ultron (2015)",
            "The Dark Knight Rises (2012)",
            "Shrek 2 (2004)",
            "E. T. The Extra-Terrestrial (1982)",
            "The Hunger Games: Catching Fire (2013)",
            "Pirates of the Caribbean: Dead Man's Chest (2006)",
            "The Lion King (1994)",
            "Toy Story 3 (2010)",
            "Iron Man 3 (2013)",
            "Captain America: Civil War (2016)",
            "The Hunger Games (2012)",
            "Spider-Man (2002)",
            "Wonder Woman (2017)",
            "Jurassic Park (1993)",
            "Transformers: Revenge of the Fallen (2009)",
            "Frozen (2013)",
            "Guardians of the Galaxy Vol. 2 (2017)",
            "Harry Potter and the Deathly Hallows, Part 2 (2011)",
            "Finding Nemo (2003)",
            "Star Wars: Episode III - Revenge of the Sith (2005)",
            "The Lord of the Rings: The Return of the King (2003)",
            "Spider-Man 2 (2004)",
            "The Passion of the Christ (2004)",
            "The Secret Life of Pets (2016)",
            "Despicable Me 2 (2013)",
            "The Jungle Book (2016)",
            "Deadpool (2016)",
            "Inside Out (2015)",
            "Furious 7 (2015)",
            "Transformers: Dark of the Moon (2011)",
            "American Sniper (2014)",
            "The Lord of the Rings: The Two Towers (2002)",
            "Zootopia (2016)",
            "The Hunger Games: Mockingjay - Part 1 (2014)",
            "Spider-Man 3 (2007)",
            "Minions (2015)",
            "Alice in Wonderland (2010)",
            "Guardians of the Galaxy (2014)",
            "Batman v Superman: Dawn of Justice (2016)",
            "Forrest Gump (1994)",
            "Suicide Squad (2016)",
            "Shrek the Third (2007)",
            "Transformers (2007)",
            "Iron Man (2008)",
            "Harry Potter and the Sorcerer's Stone (2001)",
            "Indiana Jones and the Kingdom of the Crystal Skull (2008)",
            "The Lord of the Rings: The Fellowship of the Ring (2001)",
            "Iron Man 2 (2010)",
            "Star Wars: Episode II - Attack of the Clones (2002)",
            "Pirates of the Caribbean: At World's End (2007)",
            "Star Wars: Episode VI - Return of the Jedi (1983)",
            "Spider-Man: Homecoming (2017)",
            "Independence Day (1996)",
            "Pirates of the Caribbean: The Curse of the Black Pearl (2003)",
            "Skyfall (2012)",
            "The Hobbit: An Unexpected Journey (2012)",
            "Harry Potter and the Half-Blood Prince (2009)",
            "The Twilight Saga: Eclipse (2010)",
            "The Twilight Saga: New Moon (2009)",
            "Harry Potter and the Deathly Hallows, Part 1 (2010)",
            "The Sixth Sense (1999)",
            "Up (2009)",
            "Inception (2010)",
            "The Twilight Saga: Breaking Dawn, Part 2 (2012)",
            "Harry Potter and the Order of the Phoenix (2007)",
            "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe (2005)",
            "Man of Steel (2013)",
            "Star Wars: Episode V - The Empire Strikes Back (1980)",
            "Harry Potter and the Goblet of Fire (2005)",
            "Monsters, Inc. (2001)",
            "Home Alone (1990)",
            "The Hunger Games: Mockingjay - Part 2 (2015)",
            "The Matrix Reloaded (2003)",
            "The Twilight Saga: Breaking Dawn, Part 1 (2011)",
            "Meet the Fockers (2004)",
            "The Hangover (2009)",
            "Gravity (2013)",
            "Sing (2016)",
            "Monsters University (2013)",
            "Shrek (2001)",
            "The Amazing Spider-Man (2012)",
            "Harry Potter and the Chamber of Secrets (2002)",
            "The Incredibles (2004)",
            "Dr. Seuss' How the Grinch Stole Christmas (2000)",
            "Jaws (1975)",
            "Captain America: The Winter Soldier (2014)",
            "The Hobbit: The Desolation of Smaug (2013)",
            "The LEGO Movie (2014)",
            "Star Trek (2009)"
        };
    }
}
